language: python
python:
    - "3.8"
service:
  - docker
before_install:
  - docker build -t tommywenjiezhang/web_part1_assignment -f app/Dockerfile.dev ./app
script:
  docker run tommywenjiezhang/web_part1_assignment pytest test
