language: python
python:
    - "3.8"
service:
  - docker
before_install:
  - cd app
  - docker build . -t tommywenjiezhang/web_part1_assignment -f Dockerfile.dev
script:
  docker run tommywenjiezhang/web_part1_assignment
