version: "3"
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: flask_app_container
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  db:
      image: mysql:5.7
      container_name: "MySQL_Database_Flask"
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    stdin_open: true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
      - client
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"