version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: flask_app_container
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  db:
      image: mysql:5.7
      container_name: "MySQL_Database_Flask"
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - "db:MySQL_Database_Node"
    ports:
      - 8080:80
    volumes:
      - /sessions